### PR TITLE
Reflect VAT changes in Estonia & Austria

### PR DESCRIPTION
**Pull request by stayhero**
Since Jan 1, 2016, the following changes are in effect:

Austria
Reducted rate increased from 10% to 13%

Estonia
Reduced rate increased from 9% to 14%

### CODE REVIEW

**Comment by stayhero** [comment]
I read on http://www.data-basics.com/blog/expense/2015/08/european-vat-changes about the upcoming VAT changes in Austria and checked with my tax consultant if there were any other changes effective from 2016-01-01.

He told me that from Jan 1st the VAT rates in Austria and Estonia changed as well (besides Romania). He told me that this is 100% sure (but is not able to quote it because this information is given in his DATEV tax software and not freely available).

I didn't found any information on the estonian website. The austrian change seems to be reflected on VATlive as well, but not the estonian change.

**Comment by bountin** [comment]
Austria isn't increasing it's primary reduced tax rate from 10% to 13% but the second reduced one from 12% to 13%. Further some products and services are moved from the first reduced one (10%) to the second one (previously 12%, now 13%).

Information by the Austrian finance ministry (sadly no English translation available): https://www.bmf.gv.at/steuern/selbststaendige-unternehmer/umsatzsteuer/Steuerreformgesetz_2015-2016.html

**Comment by stayhero** [comment]
@bountin I'm confused. Your source it legit, but I'm confused because currently we don't have two reduced rates. You mean the parking rate? Therefore... the reduced rate stays unchanged and the parking rate increases from 12% to 13%, is that correct? 

I'm not sure about Estonia anymore...I will contact my tax consultant again because he obviously was wrong about the Austria changes (as well as VATlive and the data-basics.com post I stated).

**Comment by adamcooke** [comment]
I tend to use this as my authoritative source... http://www.vatlive.com/vat-rates/european-vat-rates/eu-vat-rates which doesn't suggest changes to Estonia's rate. 

We currently have three rates for Austria: standard, reduced & parking. I don't know what any of these should be set to. The site above lists two rates (13% and 10%).

The European Commission really needs to publish an authoritative source of all VAT rates for all EC countries. It is impossible for businesses to keep track of the rates for every country directly and the information online is totally inaccurate most of the time.

**Comment by bountin** [comment]
Yes Austria is a bit special: The 13% "parking" rate was previously only used very sparsely [1] but as the state needs more money they moved more products and services up from the lower reduced rate effective from January 1 this year. ([1] just wine produced directly at a wine yard!)

By the way the latest EC directive does not even mention the parking rate but allows up to two reduced rates: http://eur-lex.europa.eu/legal-content/EN-DE/TXT/?uri=URISERV:l31057&from=EN

**Comment by stayhero** [comment]
@adamcooke According to my information the reduced rate increased to 13%, but this is most likely wrong. The source @bountin  posted states only that the standard rate will be left untouched at 20%, and there will be two other rates: 13% and 10%. 

It's seems likely that they increased the parked rate by 1% to 12%, and left the reduced rate untouched. But unfortunately I don't find any references about such terms (reduced, parked) in their document.

Hence, I *guess* the new rates for Austria are:

* Standard: 20%
* Reduced: 10%
* Parking: 13% (from 12% previously)

@adamcooke It's indeed all a mess. :-) According to the latest official [EU VAT rates PDF](http://ec.europa.eu/taxation_customs/resources/documents/taxation/vat/how_vat_works/rates/vat_rates_en.pdf) the reduced rate of 10% had to be applied in Austria for goods suchs as foodstuff, water supplies, pharmaceutical products. 

The Parking Rate only partly on Wine (see page 15, 2nd row) *Wine from farm production carried out by the producing farmer*.

According the the source linked by @bountin the "new" 13% will be applied to wine (sold by the farmer), hence I'm quite sure that they increased the parking rate. As they added, like @bountin said, a bunch of other product categories to the 13% rate, I'm not sure if Austria will still call it the "Parking Rate" or if they rather introduce it as "Reduced-1", "Reduced-2" like other countries.

For now I would vote to simply increase the parking rate to 13%. And wait for the official document released by the EU to see if they "rename" the rate.

**Comment by adamcooke** [comment]
I found this page on the EC website (with the help of HMRC - the UK tax authority) which says latest data as of 6/1/16. It's the most official thing I have to go on really.

http://ec.europa.eu/taxation_customs/tic/public/vatRates/vatrates.html

It does, however, claim that Romania's rate is 24% however I have read multiple places that it has changed to 20% (which is reflected in this repo).

**Comment by stayhero** [comment]
@adamcooke That source is not accurate; as far as I understand it only lists the standard rates and eventually discounted rates for digital services. I believe it is intended to help businesses with the new MOSS requirements. 

> The VAT rates indicated below **are the applicable standard rates** in each EU country **as well as 
> the VAT rate applied to the supplies of telecommunications, broadcasting and electronically 
> supplied services**.

For example: for Austria it only shows 20% standard rate and 10% reduced rate for telecommunication. For Germany it misses the 7% reduced rate. 

It would be nice to have such a database for all regular rates, not just for MOSS.

**Comment by stayhero** [comment]
@adamcooke  My tax consultant forwarded me the information he got from DATEV (quasi-monopolist in Germany / sells software for tax consultants). It indeed states that on Jan 1,2016 the rates for three countries changed:

**Austria**
A new reduced VAT rate of 13% is introduced. 

**Estonia**
A new reduced VAT rate of 14% is introduced.

**Romania**
Standard Rate is decreased from 24% to 20%. 

To me it looks as this information is true because normally DATEV is a very creditable source (used by most tax consultants in Germany... really huge company).

Nonetheless... would you probably merge this pull request concerning the Austrian changes?

**Comment by stayhero** [comment]
@adamcooke Are there any concerns regarding this PR? If not, I'd really like to see this merged (we use your gem in production and have quite a bit  Austrian customers). 

Either my suggestion or introducing another reduced-2 rate and renaming reduced to "reduced-1" and probably keep the parking rate for historical reasons? 

On a long-term strategy it may be worthwhile to implement some information about renamed rates (kind of mapping) which can be used if, like in this AT case, a country is introducing a new rate and removing another  one (where the older ones affected products and services were assigned the new rate)?

**Comment by stayhero** [comment]
Today I got an email from a customer who requested to support the 13% rate for Austria.  

What are the concerns implementing this change? 

Additionally I discovered an updated official PDF from the EU which confirms be the rate:

http://ec.europa.eu/taxation_customs/resources/documents/taxation/vat/how_vat_works/rates/vat_rates_en.pdf

**Comment by adamcooke** [comment]
The updated PDF is very handy. I will make sure that all the rates are updated to reflect it in a moment :)

**Comment by stayhero** [comment]
Yes. The evolutionary overview (page 19ff) is nice. It's sad that the EU does not update it on time.

It seems we also missed a change of the Greece reduced rate (6.5 down to 6) in Jule '15.

**Comment by adamcooke** [comment]
I have updated Austria, Greece and Luxembourg so they match the latest document.

**Pull request closed without merging**
