### PR TITLE
Update france.rb

### PR DESCRIPTION
**Pull request by bpolaszek**
Source (fr): https://fr.wikipedia.org/wiki/Taxe_sur_la_valeur_ajout%C3%A9e_en_France

### CODE REVIEW

**Comment by adamcooke** [comment]
Can you quote a government source for this change? Wikipedia isn't really a suitable source for this information.

**Comment by bpolaszek** [comment]
Hi @adamcooke,

Well, as far as I remember, France had 3 rates in the past:
super_reduced: 2.1
reduced1: 5.5
standard: 19.6

Then, on 2012, January 1st, some exceptions were added to the reduced rate, that lead to:
super_reduced: 2.1
reduced1: 5.5
reduced2: 7
standard: 19.6

Then on 2014, January 1st, 2 transformations were made:
reduced2: 10
standard: 20

Here are some related (fr) links (which quote the original 2012 state):
http://www.economie.gouv.fr/cedef/taux-tva-france-et-union-europeenne
http://www.economie.gouv.fr/vous-orienter/particulier/consommation-impots/differents-taux-tva

**Comment by Mark-H** [comment]
These rates are also confirmed in the official EC document at  https://ec.europa.eu/taxation_customs/sites/taxation/files/resources/documents/taxation/vat/how_vat_works/rates/vat_rates_en.pdf - page 20 shows the historic VAT rates.

**Comment by bpolaszek** [comment]
@Mark-H Great! :tada:

**Comment by adamcooke** [comment]
Thanks @Mark-H for verifying this.

**Comment by bpolaszek** [comment]
Thank you @adamcooke.

**Pull request merged**
